name: Deploy to Firebase (Live)

on:
  push:
    branches:
      - fernando

jobs:
  deploy-live:
    name: Deploy to Firebase Live
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Live
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SECONDBYTE33 }}
          channelId: live
          projectId: secondbyte-4804a